---
title: "Lab 04 - Visualizing spatial data. La Quinta is Spanish for next to Denny's, Pt. 1"
author: "Yuxin Xie"
date: "2/7/25"
output: github_document
---

### Load packages and data
```{r load-packages, message = FALSE}
#install.packages("devtools")
#devtools::install_github("rstudio-education/dsbox")
library(tidyverse) 
library(dsbox) 
```

```{r load-data, message = FALSE}
D <- dsbox::dennys
LQ <- dsbox::laquinta
states <- read_csv("data/states.csv")
```

### Exercise 1
```{r dimensions of the Dennys dataset}
cat ("There are", nrow (D), "rows and", ncol(D), "variables in the Dennys dataset.", "\n") 

###There are six variables: address, city, state, zip code, longitude, and latitude. Each row represents one Denny's store. 
```

### Exercise 2
```{r dimensions of the La Quinta dataset}
cat ("There are", nrow (LQ), "rows and", ncol(LQ), "variables in the Laquinta dataset.", "\n") 

###There are six variables: address, city, state, zip code, longitude, and latitude. Each row represents one La Quinta store. 
```
### Exercise 3
```{r any La Quinta and Dennys locations outside of the US?}
## from the website, La Quinta has some stores across the world, for instance, in South America: Chile, Colombia, Ecuador. In Asia: China. In Europe: Turkey. 
## All Danny's stores are in the US.
```

### Exercise 4
```{r any Dennys and La Quinta locations outside of the US?}
##Denny's 
non_us_states_D<-setdiff(states$abbreviation, D$state)
print(non_us_states_D)
##all Denny's stores are in the US

##La Quinta 
non_us_states_LQ<-setdiff(LQ$state, states$abbreviation)
print(non_us_states_LQ)
## There are stores in "AG"  "QR"  "CH"  "NL"  "ANT" "ON"  "VE"  "PU"  "SL"  "FM"  "BC" outside of the US. 
```


### Exercise 5
```{r Dennys locations outside the US}
##Denny's locations outside the US
D %>%
  filter(!(state %in% states$abbreviation))
##Note that the %in% operator matches the states listed in the state variable to those listed in states$abbreviation. The ! operator means not. 
```

### Exercise 6
```{r Add a country variable to the Dennys dataset}
D_US<-D %>%
  mutate(country = "United States")
## D_US<-will assign the result to D_US, if just run dn %>%
  #mutate(country = "United States"), It modifies the dataset temporarily but does not save the changes. 
```

### Exercise 7
```{r La Quinta locations outside the US}
LQ_NUS<-LQ %>%
  filter(!(state %in% states$abbreviation))
print (LQ_NUS$state)
print (LQ_NUS$address)
print (LQ_NUS$zip)
## countries: Mexico, Colombia, Canada, and Honduras
## Mexico: AG, QR, CH, NL, VE, PU, SL, 
## Colombia: ANT
## Canada: ON, BC
## Honduras: FM
```

### Exercise 8
```{r Add a country variable to the La Quinta dataset}
## countries: Mexico, Colombia, Canada, and Honduras
## Mexico: AG, QR, CH, NL, VE, PU, SL, 
## Colombia: ANT
## Canada: ON, BC
## Honduras: FM
LQ_country<-LQ %>%
  mutate(country = case_when(
    state %in% state.abb ~ "United States",
    state %in% c("ON", "BC") ~ "Canada",
    state == "ANT" ~ "Colombia",
    state == "FM" ~ "Honduras",
    state %in% c("AG", "QR", "CH", "NL", "VE", "PU", "SL") ~ "Mexico"
  ))
##Going forward we will work with the data from the United States only. 
##filter the La Quinta dataset for locations in United States.
LQ_US <- LQ_country %>%
  filter(country == "United States")
```

### Exercise 9 (1)
```{r most and fewest}
##Which states have the most and fewest Denny’s locations? What about La Quinta? 
# Descending order (highest to lowest)
D_US_desc <- D_US %>%
  group_by(state) %>%
  count(state) %>%
  arrange(desc(n))
# Ascending order (lowest to highest)
D_US_asc <- D_US %>%
  group_by(state) %>%
  count(state) %>%
  arrange(n)
# Print both
print("Descending Order:")
print(D_US_desc)

print("Ascending Order:")
print(D_US_asc)
## CA, California has the most Denny’s locations
## DE, Delaware has the fewest Denny’s locations

# Descending order (highest to lowest)
LQ_US_desc <- LQ_US %>%
  group_by(state) %>%
  count(state) %>%
  arrange(desc(n))
# Ascending order (lowest to highest)
LQ_US_asc <- LQ_US %>%
  group_by(state) %>%
  count(state) %>%
  arrange(n)
# Print both
print("Descending Order:")
print(LQ_US_desc)

print("Ascending Order:")
print(LQ_US_asc)
## TX, Texas has the most La Quinta locations
## ME, Maine has the fewest La Quinta locations
```

### Exercise 9 (2)
```{r count how many observations are in each state}
## count how many observations are in each state
D_US_2<-D_US %>%
  count(state) %>%
  inner_join(states, by = c("state" = "abbreviation"))

LQ_US_2<-LQ_US %>%
  count(state) %>%
  inner_join(states, by = c("state" = "abbreviation"))
  
```

### Exercise 10
```{r most locations per thousand square miles}
##Which states have the most Denny’s locations per thousand square miles? What about La Quinta?
D_US_2 %>%
  mutate (per = (n / area) * 1000) %>%
  arrange (desc(per))
##DC has the most Denny’s locations per thousand square miles

LQ_US_2 %>%
  mutate (per = (n / area) * 1000) %>%
  arrange (desc(per))
## RI has the most La Quinta locations per thousand square miles

## put the two datasets together into a single data frame. 
## However before we do so, we need to add an identifier variable. 
D_US <- D_US %>%
  mutate(establishment = "Denny's")
LQ_US <- LQ_US %>%
  mutate(establishment = "La Quinta")

##Because the two data frames have the same columns, we can easily bind them with the bind_rows function
D_LQ <- bind_rows(D_US, LQ_US)

## plot the locations of the two establishments using a scatter plot
## color the points by the establishment type.
## latitude is plotted on the x-axis and the longitude on the y-axis.
ggplot(D_LQ, mapping = aes(
  x = longitude,
  y = latitude,
  color = establishment
)) +
  geom_point()

```

### Exercise 11

```{r NC_plot}
##Filter the data for observations in North Carolina only, and recreate the plot
##You should also adjust the transparency of the points, by setting the alpha level, so that it’s easier to see the overplotted ones. 
D_LQ_NC <- D_LQ %>%
  filter(state == "NC")

ggplot(D_LQ_NC, mapping = aes(
  x = longitude,
  y = latitude,
  color = establishment
)) +
  borders("state", regions = "north carolina", colour = "gray50", fill = NA) +  # Adds NC border+
  geom_point(alpha = 0.5)+
  theme_minimal() +
  labs(title = "Denny's and La Quinta Locations in North Carolina",
       x = "Longitude",
       y = "Latitude",
       color = "Establishment Type")
##Visually, does Mitch Hedberg’s joke appear to hold here?
## La Quinta next to Denny’s?
## The data does not support Mitch Hedberg’s joke. La Quinta and Denny’s locations do not consistently appear near each other.

```

### Exercise 12

```{r Texas_plot}
##filter the data for observations in Texas only, and recreate the plot, with an appropriate alpha level. 
D_LQ_TX <- D_LQ %>%
  filter(state == "TX")

ggplot(D_LQ_TX, mapping = aes(
  x = longitude,
  y = latitude,
  color = establishment
)) +
  borders("state", regions = "Texas", colour = "gray50", fill = NA) +  # Adds TX border
  geom_point(alpha = 0.3)+
  theme_minimal() +
  labs(title = "Denny's and La Quinta Locations in North Carolina",
       x = "Longitude",
       y = "Latitude",
       color = "Establishment Type")
##Visually, does Mitch Hedberg’s joke appear to hold here?
## La Quinta next to Denny’s?
## The data does not support Mitch Hedberg’s joke. La Quinta and Denny’s locations do not consistently appear near each other.

```





